"""fix candidates schema with enrichment fields

Revision ID: 1123f08f2955
Revises: 
Create Date: 2026-05-03 16:31:13.048301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1123f08f2955'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.alter_column('skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('links',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('projects',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::text"))
        batch_op.alter_column('github_top_languages',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::text"))
        batch_op.alter_column('github_repos_data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::text"))
        batch_op.alter_column('resume_skills',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::text"))
        batch_op.alter_column('resume_projects',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::text"))
        batch_op.alter_column('agent_statuses',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text"))
        batch_op.alter_column('top_job_matches',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::text"))
        batch_op.drop_index(batch_op.f('idx_candidates_user_id'))
        batch_op.drop_constraint(batch_op.f('candidates_preferred_region_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'regions', ['preferred_region_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('recruiters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_recruiters_user_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)

    with op.batch_alter_table('recruiters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_recruiters_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('candidates_preferred_region_id_fkey'), 'regions', ['preferred_region_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_candidates_user_id'), ['user_id'], unique=False)
        batch_op.alter_column('top_job_matches',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::text"))
        batch_op.alter_column('agent_statuses',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text"))
        batch_op.alter_column('resume_projects',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::text"))
        batch_op.alter_column('resume_skills',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::text"))
        batch_op.alter_column('github_repos_data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::text"))
        batch_op.alter_column('github_top_languages',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::text"))
        batch_op.alter_column('projects',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'::text"))
        batch_op.alter_column('links',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('skills',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))

    # ### end Alembic commands ###
