"""add job alerts tables

Revision ID: e0744c269d78
Revises: 1123f08f2955
Create Date: 2026-05-03 19:35:25.237002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0744c269d78'
down_revision = '1123f08f2955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidatescore', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidatescore_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_candidatescore_jd_hash'))

    op.drop_table('candidatescore')
    with op.batch_alter_table('candidatecache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidatecache_candidate_id'))

    op.drop_table('candidatecache')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.alter_column('skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('links',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('projects',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('github_top_languages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('github_repos_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('resume_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('resume_projects',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('agent_statuses',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.alter_column('top_job_matches',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.drop_index(batch_op.f('idx_candidates_user_id'))
        batch_op.drop_constraint(batch_op.f('candidates_preferred_region_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'regions', ['preferred_region_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('feedback_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_resources', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('task_checklist', sa.JSON(), nullable=True))

    with op.batch_alter_table('recruiters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_recruiters_user_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)

    with op.batch_alter_table('recruiters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_recruiters_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('feedback_reports', schema=None) as batch_op:
        batch_op.drop_column('task_checklist')
        batch_op.drop_column('learning_resources')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('candidates_preferred_region_id_fkey'), 'regions', ['preferred_region_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_candidates_user_id'), ['user_id'], unique=False)
        batch_op.alter_column('top_job_matches',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('agent_statuses',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.alter_column('resume_projects',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('resume_skills',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('github_repos_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('github_top_languages',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('projects',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('links',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('skills',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))

    op.create_table('candidatecache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('schema_version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('profile_json', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('collected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ttl_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('candidatecache_pkey'))
    )
    with op.batch_alter_table('candidatecache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidatecache_candidate_id'), ['candidate_id'], unique=True)

    op.create_table('candidatescore',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jd_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('candidate_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('github', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('leetcode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('composite_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tier', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rationale', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('components', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('candidatescore_pkey')),
    sa.UniqueConstraint('jd_hash', 'candidate_id', name=op.f('candidatescore_jd_hash_candidate_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('candidatescore', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidatescore_jd_hash'), ['jd_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidatescore_candidate_id'), ['candidate_id'], unique=False)

    # ### end Alembic commands ###
